### PR TITLE
Create and delete topic methods.

### PR DESCRIPTION
**Pull request by ayoze**
Just added and tested those two methods to create and delete topics.

### CODE REVIEW

**Comment by mcfedr** [comment]
The main reason I didn't include these is that there is no reason why you shouldn't just access the `SnsClient`(`mcfedr_aws_push.sns_client` ) directly

**Comment by ayoze** [comment]
Sure, but what is the point of the bundle then? I'd prefer to have a bundle with easy SNS commands ready-to-be-called.

**Comment by mcfedr** [comment]
I'll merge the methods, but I'm going to mark them as `@deprecated` like the rest of this class.

I think its just as easy to call

    $this->get('mcfedr_aws_push.sns_client')->deleteTopic([
        'TopicArn' => $topicArn
    ]);

As 

   $this->get('mcfedr_aws_push.topics')->deleteTopic($topicArn);

**Comment by ayoze** [comment]
Yes, I know we can call via the sns_client, but I think that your bundle implements a layer over it so we don't need to call the original methods... passing the ['TopicArn' => ...] array is so much dependent of the API, that's why I, personally, prefer a deleteTopic( $arn ) call, and similar ones, of course.

**Comment by mcfedr** [comment]
I see the bundle as more being a helper. It makes it easy to send messages, by generating the correct JSON, and it makes it easy to put the settings in configuration.

**Pull request merged**
